In [1]:
import numpy as np

In [2]:
A = np.random.rand(3, 4)
A

array([[0.93101687, 0.12200244, 0.86369212, 0.04178564],
       [0.10625138, 0.78818902, 0.41565865, 0.82892515],
       [0.07313904, 0.51245916, 0.88071317, 0.80398941]])

In [3]:
AT = A.T
AT

array([[0.93101687, 0.10625138, 0.07313904],
       [0.12200244, 0.78818902, 0.51245916],
       [0.86369212, 0.41565865, 0.88071317],
       [0.04178564, 0.82892515, 0.80398941]])

In [4]:
AI = np.linalg.inv(A)
AI

LinAlgError: Last 2 dimensions of the array must be square

In [5]:
Ai = np.linalg.pinv(A)
Ai

array([[ 0.95788283,  0.91722818, -1.26475082],
       [ 0.11908142,  1.44917702, -1.00033862],
       [ 0.12284771, -1.20876782,  1.48685225],
       [-0.29761162,  0.31697992,  0.3677225 ]])

In [6]:
np.dot(A, Ai)

array([[ 1.00000000e+00, -1.89774312e-16,  2.23236502e-16],
       [ 2.03681981e-16,  1.00000000e+00, -7.82971506e-17],
       [ 1.66650403e-16,  1.01158710e-16,  1.00000000e+00]])

In [7]:
np.matmul(A, Ai)

array([[ 1.00000000e+00, -1.89774312e-16,  2.23236502e-16],
       [ 2.03681981e-16,  1.00000000e+00, -7.82971506e-17],
       [ 1.66650403e-16,  1.01158710e-16,  1.00000000e+00]])

In [8]:
As = np.random.rand(3, 3)
As

array([[0.04276163, 0.85020953, 0.11215454],
       [0.72271767, 0.67980722, 0.424023  ],
       [0.28125194, 0.08452307, 0.13491812]])

In [9]:
Asi = np.linalg.inv(As)
Asi

array([[  8.88562883, -16.73317369,  45.20287524],
       [  3.45854704,  -4.09855432,  10.00599155],
       [-20.68978835,  37.44982457, -93.0870768 ]])

In [10]:
np.matmul(As, Asi)

array([[ 1.00000000e+00, -6.78611948e-16,  1.33768033e-16],
       [ 2.51673400e-17,  1.00000000e+00, -1.57613619e-15],
       [ 5.25566155e-16,  1.46631750e-16,  1.00000000e+00]])

In [11]:
np.dot(As, Asi)

array([[ 1.00000000e+00, -6.78611948e-16,  1.33768033e-16],
       [ 2.51673400e-17,  1.00000000e+00, -1.57613619e-15],
       [ 5.25566155e-16,  1.46631750e-16,  1.00000000e+00]])

In [18]:
Ii = np.random.rand(3, 3)
I = np.dot(As, Asi)
for i in range(3):
    for j in range(3):
        Ii[i][j] = int(I[i][j])
        pass
    pass
Ii

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
B = np.random.randint(0, 10, (3, 3))
B

array([[1, 8, 2],
       [7, 7, 9],
       [0, 6, 2]])

In [22]:
Bi = np.linalg.inv(B)
Bi

array([[ 0.58823529,  0.05882353, -0.85294118],
       [ 0.20588235, -0.02941176, -0.07352941],
       [-0.61764706,  0.08823529,  0.72058824]])

In [24]:
Ib = np.dot(B, Bi)
Ib

array([[ 1.00000000e+00,  2.77555756e-17,  0.00000000e+00],
       [-4.44089210e-16,  1.00000000e+00,  8.88178420e-16],
       [ 0.00000000e+00,  2.77555756e-17,  1.00000000e+00]])